// Mock data for development and demo purposes
import type { Car, Auction, User, Seller } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'car_enthusiast_99',
    email: 'user1@example.com',
    firstName: 'John',
    lastName: 'Doe',
    rating: 4.8,
    reviewCount: 127,
    memberSince: '2020-01-15',
    location: {
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      displayName: 'Miami, FL',
    },
  },
  {
    id: 'user-2',
    username: 'speed_demon',
    email: 'user2@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    rating: 4.9,
    reviewCount: 203,
    memberSince: '2019-06-20',
    location: {
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      displayName: 'Los Angeles, CA',
    },
  },
];

export const mockSellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Elite Motors',
    type: 'Verified Dealer',
    rating: 4.9,
    reviewCount: 450,
    verified: true,
  },
  {
    id: 'seller-2',
    name: 'John Doe',
    type: 'Private Seller',
    rating: 4.7,
    reviewCount: 23,
    verified: true,
  },
  {
    id: 'seller-3',
    name: 'Premium Auto Group',
    type: 'Pro Seller',
    rating: 5.0,
    reviewCount: 892,
    verified: true,
  },
];

export const mockCars: Car[] = [
  {
    id: 'car-1',
    year: 2019,
    make: 'Porsche',
    model: '911',
    trim: 'Carrera S',
    type: 'Coupe',
    mileage: 22400,
    mileageDisplay: '22,400 mi',
    transmission: 'PDK',
    fuel: 'Gasoline',
    color: 'Racing Yellow',
    vin: 'WP0AB2A99KS123456',
    condition: 'Excellent',
    description: 'Immaculate 2019 Porsche 911 Carrera S with low mileage. Single owner, garage kept, all service records available. This stunning example features the Sport Chrono Package, PASM suspension, and premium interior upgrades. No accidents, clean CarFax. Perfect for the discerning enthusiast.',
    images: [
      '/images/porsche-911.jpg',
      '/images/porsche-911.jpg',
      '/images/porsche-911.jpg',
    ],
    location: {
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      country: 'USA',
      displayName: 'Miami, FL',
    },
    seller: mockSellers[0],
    specifications: {
      engine: '3.0L Twin-Turbo Flat-6',
      horsepower: 443,
      torque: 390,
      drivetrain: 'RWD',
      seats: 4,
      doors: 2,
      mpgCity: 20,
      mpgHighway: 26,
      fuelCapacity: 16.9,
    },
    features: [
      'Sport Chrono Package',
      'PASM Suspension',
      'Premium Sound System',
      'Leather Interior',
      'Navigation System',
      'Parking Sensors',
      'Backup Camera',
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: 'car-2',
    year: 2018,
    make: 'BMW',
    model: 'M4',
    trim: 'Competition',
    type: 'Coupe',
    mileage: 31200,
    mileageDisplay: '31,200 mi',
    transmission: 'DCT',
    fuel: 'Gasoline',
    color: 'Alpine White',
    vin: 'WBS3R9C50JK123789',
    condition: 'Very Good',
    description: 'Powerful 2018 BMW M4 Competition with DCT transmission. Well-maintained with regular service. Includes M Performance exhaust and carbon fiber accents. Perfect for track days or spirited driving.',
    images: [
      '/images/bmw-m4.jpg',
      '/images/bmw-m4.jpg',
      '/images/bmw-m4.jpg',
    ],
    location: {
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'USA',
      displayName: 'Los Angeles, CA',
    },
    seller: mockSellers[1],
    specifications: {
      engine: '3.0L Twin-Turbo I6',
      horsepower: 444,
      torque: 406,
      drivetrain: 'RWD',
      seats: 4,
      doors: 2,
      mpgCity: 17,
      mpgHighway: 26,
      fuelCapacity: 15.8,
    },
    features: [
      'M Performance Exhaust',
      'Carbon Fiber Trim',
      'Harman Kardon Sound',
      'Adaptive M Suspension',
      'M Sport Brakes',
    ],
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: 'car-3',
    year: 2021,
    make: 'Mercedes-AMG',
    model: 'C63',
    trim: 'S',
    type: 'Sedan',
    mileage: 18900,
    mileageDisplay: '18,900 mi',
    transmission: 'Automatic',
    fuel: 'Gasoline',
    color: 'Obsidian Black',
    vin: 'WDDWF4KB1MR123456',
    condition: 'Excellent',
    description: 'Like-new 2021 Mercedes-AMG C63 S with minimal miles. Fully loaded with every option. AMG Performance Package, carbon ceramic brakes, and premium interior. Perfect condition, no stories.',
    images: [
      '/images/mercedes-c63.jpg',
      '/images/mercedes-c63.jpg',
      '/images/mercedes-c63.jpg',
    ],
    location: {
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      displayName: 'New York, NY',
    },
    seller: mockSellers[2],
    specifications: {
      engine: '4.0L Twin-Turbo V8',
      horsepower: 503,
      torque: 516,
      drivetrain: 'RWD',
      seats: 5,
      doors: 4,
      mpgCity: 18,
      mpgHighway: 27,
      fuelCapacity: 17.4,
    },
    features: [
      'AMG Performance Package',
      'Carbon Ceramic Brakes',
      'Burmester Sound System',
      'AMG Track Package',
      'Premium Leather',
      'Panoramic Sunroof',
    ],
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-19T16:00:00Z',
  },
  {
    id: 'car-4',
    year: 2020,
    make: 'Audi',
    model: 'R8',
    trim: 'Performance',
    type: 'Coupe',
    mileage: 15200,
    mileageDisplay: '15,200 mi',
    transmission: 'DCT',
    fuel: 'Gasoline',
    color: 'Nardo Gray',
    vin: 'WUAAUAFG0L7901234',
    condition: 'Excellent',
    description: 'Stunning 2020 Audi R8 Performance with V10 power. Rare Nardo Gray color. Low miles, perfect condition. Includes carbon fiber package and premium sound system.',
    images: [
      '/images/audi-r8.jpg',
      '/images/audi-r8.jpg',
      '/images/audi-r8.jpg',
    ],
    location: {
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      country: 'USA',
      displayName: 'Miami, FL',
    },
    seller: mockSellers[0],
    specifications: {
      engine: '5.2L V10',
      horsepower: 602,
      torque: 413,
      drivetrain: 'AWD',
      seats: 2,
      doors: 2,
      mpgCity: 13,
      mpgHighway: 20,
      fuelCapacity: 19.3,
    },
    features: [
      'Carbon Fiber Package',
      'Bang & Olufsen Sound',
      'Audi Virtual Cockpit',
      'Carbon Ceramic Brakes',
      'Sport Exhaust',
    ],
    createdAt: '2024-01-08T11:00:00Z',
    updatedAt: '2024-01-17T10:00:00Z',
  },
  {
    id: 'car-5',
    year: 2017,
    make: 'Chevrolet',
    model: 'Camaro',
    trim: 'SS',
    type: 'Coupe',
    mileage: 28500,
    mileageDisplay: '28,500 mi',
    transmission: 'Manual',
    fuel: 'Gasoline',
    color: 'Red Hot',
    vin: '1G1FH1R75H0123456',
    condition: 'Very Good',
    description: '2017 Chevrolet Camaro SS with 6-speed manual. Well-maintained, garage kept. Perfect for the manual transmission enthusiast.',
    images: [
      '/images/camaro-ss.jpg',
      '/images/camaro-ss.jpg',
      '/images/camaro-ss.jpg',
    ],
    location: {
      city: 'Dallas',
      state: 'TX',
      zipCode: '75201',
      country: 'USA',
      displayName: 'Dallas, TX',
    },
    seller: mockSellers[1],
    specifications: {
      engine: '6.2L V8',
      horsepower: 455,
      torque: 455,
      drivetrain: 'RWD',
      seats: 4,
      doors: 2,
      mpgCity: 16,
      mpgHighway: 25,
      fuelCapacity: 19.0,
    },
    features: [
      '6-Speed Manual',
      'Bose Sound System',
      'Performance Package',
      'Leather Seats',
    ],
    createdAt: '2024-01-05T07:00:00Z',
    updatedAt: '2024-01-15T13:00:00Z',
  },
  {
    id: 'car-6',
    year: 2019,
    make: 'Dodge',
    model: 'Challenger',
    trim: 'SRT Hellcat',
    type: 'Coupe',
    mileage: 19200,
    mileageDisplay: '19,200 mi',
    transmission: 'Automatic',
    fuel: 'Gasoline',
    color: 'Plum Crazy',
    vin: '2C3CDXBG9KH123456',
    condition: 'Excellent',
    description: '2019 Dodge Challenger SRT Hellcat in rare Plum Crazy color. Supercharged V8 power. Low miles, excellent condition.',
    images: [
      '/images/challenger-srt.jpg',
      '/images/challenger-srt.jpg',
      '/images/challenger-srt.jpg',
    ],
    location: {
      city: 'Phoenix',
      state: 'AZ',
      zipCode: '85001',
      country: 'USA',
      displayName: 'Phoenix, AZ',
    },
    seller: mockSellers[2],
    specifications: {
      engine: '6.2L Supercharged V8',
      horsepower: 707,
      torque: 650,
      drivetrain: 'RWD',
      seats: 5,
      doors: 2,
      mpgCity: 13,
      mpgHighway: 22,
      fuelCapacity: 18.5,
    },
    features: [
      'Supercharged V8',
      'SRT Performance Package',
      'Alcantara Interior',
      'Performance Pages',
    ],
    createdAt: '2024-01-03T06:00:00Z',
    updatedAt: '2024-01-14T11:00:00Z',
  },
  {
    id: 'car-7',
    year: 2018,
    make: 'Ford',
    model: 'Mustang',
    trim: 'GT',
    type: 'Coupe',
    mileage: 26700,
    mileageDisplay: '26,700 mi',
    transmission: 'Manual',
    fuel: 'Gasoline',
    color: 'Velocity Blue',
    vin: '1FA6P8CF5J5123456',
    condition: 'Very Good',
    description: '2018 Ford Mustang GT with 6-speed manual. Performance Package. Great condition, well-maintained.',
    images: [
      '/images/mustang-gt.jpg',
      '/images/mustang-gt.jpg',
      '/images/mustang-gt.jpg',
    ],
    location: {
      city: 'Houston',
      state: 'TX',
      zipCode: '77001',
      country: 'USA',
      displayName: 'Houston, TX',
    },
    seller: mockSellers[1],
    specifications: {
      engine: '5.0L V8',
      horsepower: 460,
      torque: 420,
      drivetrain: 'RWD',
      seats: 4,
      doors: 2,
      mpgCity: 15,
      mpgHighway: 25,
      fuelCapacity: 15.5,
    },
    features: [
      'Performance Package',
      '6-Speed Manual',
      'Shaker Pro Sound',
      'Recaro Seats',
    ],
    createdAt: '2024-01-01T05:00:00Z',
    updatedAt: '2024-01-12T09:00:00Z',
  },
  {
    id: 'car-8',
    year: 2020,
    make: 'Nissan',
    model: 'GT-R',
    trim: 'Premium',
    type: 'Coupe',
    mileage: 12300,
    mileageDisplay: '12,300 mi',
    transmission: 'DCT',
    fuel: 'Gasoline',
    color: 'Pearl White',
    vin: 'JN1AZ4EH0LM123456',
    condition: 'Excellent',
    description: '2020 Nissan GT-R Premium. Ultra-low miles. Perfect condition. All service records. Rare find.',
    images: [
      '/images/nissan-gtr.jpg',
      '/images/nissan-gtr.jpg',
      '/images/nissan-gtr.jpg',
    ],
    location: {
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
      displayName: 'Seattle, WA',
    },
    seller: mockSellers[0],
    specifications: {
      engine: '3.8L Twin-Turbo V6',
      horsepower: 565,
      torque: 467,
      drivetrain: 'AWD',
      seats: 4,
      doors: 2,
      mpgCity: 16,
      mpgHighway: 22,
      fuelCapacity: 19.5,
    },
    features: [
      'Premium Package',
      'Bose Sound System',
      'Carbon Fiber Trim',
      'Track Mode',
    ],
    createdAt: '2023-12-28T04:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
];

export const mockAuctions: Auction[] = [
  {
    id: 'auction-1',
    carId: 'car-1',
    car: mockCars[0],
    currentBid: 67500,
    startingBid: 60000,
    reservePrice: 65000,
    reserveMet: true,
    bidCount: 18,
    bids: [],
    status: 'live',
    startDate: '2024-01-15T10:00:00Z',
    endDate: '2024-01-25T14:00:00Z',
    endsIn: '2d 14h 32m',
    featured: true,
    views: 1247,
    watchers: 45,
  },
  {
    id: 'auction-2',
    carId: 'car-2',
    car: mockCars[1],
    currentBid: 41200,
    startingBid: 38000,
    reservePrice: 40000,
    reserveMet: true,
    bidCount: 24,
    bids: [],
    status: 'live',
    startDate: '2024-01-10T08:00:00Z',
    endDate: '2024-01-22T16:00:00Z',
    endsIn: '1d 8h 15m',
    featured: true,
    views: 892,
    watchers: 32,
  },
  {
    id: 'auction-3',
    carId: 'car-3',
    car: mockCars[2],
    currentBid: 55000,
    startingBid: 50000,
    reservePrice: 52000,
    reserveMet: true,
    bidCount: 12,
    bids: [],
    status: 'live',
    startDate: '2024-01-12T09:00:00Z',
    endDate: '2024-01-26T18:00:00Z',
    endsIn: '3d 6h 45m',
    featured: true,
    views: 1563,
    watchers: 67,
  },
  {
    id: 'auction-4',
    carId: 'car-4',
    car: mockCars[3],
    currentBid: 125000,
    startingBid: 110000,
    reservePrice: 120000,
    reserveMet: true,
    bidCount: 8,
    bids: [],
    status: 'live',
    startDate: '2024-01-08T11:00:00Z',
    endDate: '2024-01-24T12:00:00Z',
    endsIn: '2d 2h 10m',
    featured: false,
    views: 2341,
    watchers: 89,
  },
  {
    id: 'auction-5',
    carId: 'car-5',
    car: mockCars[4],
    currentBid: 28500,
    startingBid: 25000,
    reservePrice: 27000,
    reserveMet: true,
    bidCount: 15,
    bids: [],
    status: 'live',
    startDate: '2024-01-05T07:00:00Z',
    endDate: '2024-01-20T20:00:00Z',
    endsIn: '1d 12h 30m',
    featured: false,
    views: 567,
    watchers: 18,
  },
  {
    id: 'auction-6',
    carId: 'car-6',
    car: mockCars[5],
    currentBid: 58000,
    startingBid: 55000,
    reservePrice: 56000,
    reserveMet: true,
    bidCount: 11,
    bids: [],
    status: 'live',
    startDate: '2024-01-03T06:00:00Z',
    endDate: '2024-01-19T15:00:00Z',
    endsIn: '18h 45m',
    featured: false,
    views: 1234,
    watchers: 56,
  },
  {
    id: 'auction-7',
    carId: 'car-7',
    car: mockCars[6],
    currentBid: 32000,
    startingBid: 30000,
    reservePrice: 31000,
    reserveMet: true,
    bidCount: 9,
    bids: [],
    status: 'live',
    startDate: '2024-01-01T05:00:00Z',
    endDate: '2024-01-18T10:00:00Z',
    endsIn: '12h 20m',
    featured: false,
    views: 445,
    watchers: 14,
  },
  {
    id: 'auction-8',
    carId: 'car-8',
    car: mockCars[7],
    currentBid: 95000,
    startingBid: 90000,
    reservePrice: 92000,
    reserveMet: true,
    bidCount: 6,
    bids: [],
    status: 'live',
    startDate: '2023-12-28T04:00:00Z',
    endDate: '2024-01-17T14:00:00Z',
    endsIn: '8h 15m',
    featured: false,
    views: 1890,
    watchers: 72,
  },
];
